#!/usr/bin/env bash
# beszel-agent.sh — Install and configure the Beszel agent on a remote node.
#
# Part of the 0x10debug monitor-stack: https://github.com/0x10debug/monitor-stack
#
# Usage:
#   ./beszel-agent.sh --hub-url <url> --key <key> --node-name <name>
#
# The script is idempotent: if the beszel-agent service is already running
# with the same hub URL it will exit cleanly instead of reinstalling.

set -euo pipefail

# ─── Defaults ────────────────────────────────────────────────
HUB_URL=""
HUB_KEY=""
NODE_NAME=""
# shellcheck disable=SC2034 # used for future version pinning
BESZEL_AGENT_VERSION="latest"
INSTALL_DIR="/usr/local/bin"
SERVICE_FILE="/etc/systemd/system/beszel-agent.service"
DATA_DIR="/var/lib/beszel-agent"

# ─── Helpers ─────────────────────────────────────────────────
log()   { printf '[beszel-agent] %s\n' "$*" >&2; }
die()   { log "ERROR: $*"; exit 1; }

usage() {
    cat <<'EOF'
Usage: beszel-agent.sh --hub-url <url> --key <key> --node-name <name>

Options:
  --hub-url <url>       URL of the Beszel hub (e.g. https://monitor.example.com:8090)
  --key <key>           Agent key generated by the Beszel hub UI
  --node-name <name>    Display name for this node in the hub
  -h, --help            Show this help message
EOF
}

# ─── Parse arguments ─────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --hub-url)
            HUB_URL="$2"; shift 2 ;;
        --key)
            HUB_KEY="$2"; shift 2 ;;
        --node-name)
            NODE_NAME="$2"; shift 2 ;;
        -h|--help)
            usage; exit 0 ;;
        *)
            die "Unknown argument: $1 (use --help for usage)" ;;
    esac
done

[[ -n "$HUB_URL" ]]   || { usage; die "--hub-url is required"; }
[[ -n "$HUB_KEY" ]]   || { usage; die "--key is required"; }
[[ -n "$NODE_NAME" ]] || { usage; die "--node-name is required"; }

# ─── Preflight checks ────────────────────────────────────────
command -v systemctl   >/dev/null 2>&1 || die "systemctl not found — systemd is required"
command -v curl        >/dev/null 2>&1 || die "curl is required (install with: apt install curl)"
[[ "$(id -u)" -eq 0 ]] || die "This script must be run as root (use sudo)"

# ─── Idempotency check ───────────────────────────────────────
if systemctl is-active --quiet beszel-agent 2>/dev/null; then
    EXISTING_URL="$(systemctl cat beszel-agent 2>/dev/null \
        | grep -oP '(?<=--hub-url )[^ ]+' || true)"
    if [[ "$EXISTING_URL" == "$HUB_URL" ]]; then
        log "beszel-agent is already running and connected to $HUB_URL — nothing to do."
        exit 0
    fi
    log "beszel-agent is running with a different hub URL — reconfiguring."
    systemctl stop beszel-agent || true
fi

# ─── Download and install the binary ─────────────────────────
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64|amd64)  ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *)             die "Unsupported architecture: $ARCH" ;;
esac

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
DOWNLOAD_URL="https://github.com/henrygd/beszel/releases/latest/download/beszel-agent_${OS}_${ARCH}"
TMP_BIN="$(mktemp)"

log "Downloading beszel-agent ($OS/$ARCH) from $DOWNLOAD_URL"
if ! curl -fsSL "$DOWNLOAD_URL" -o "$TMP_BIN"; then
    rm -f "$TMP_BIN"
    die "Failed to download beszel-agent binary"
fi

chmod +x "$TMP_BIN"
mv "$TMP_BIN" "${INSTALL_DIR}/beszel-agent"
log "Installed beszel-agent to ${INSTALL_DIR}/beszel-agent"

# ─── Prepare data directory ──────────────────────────────────
mkdir -p "$DATA_DIR"

# ─── Create systemd service ──────────────────────────────────
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Beszel Agent
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=${INSTALL_DIR}/beszel-agent --hub-url ${HUB_URL} --key ${HUB_KEY} --node-name ${NODE_NAME}
Restart=on-failure
RestartSec=5
Environment=ED25519_PUBLIC_KEY=${HUB_KEY}

[Install]
WantedBy=multi-user.target
EOF

log "Created systemd service at $SERVICE_FILE"

# ─── Enable and start ────────────────────────────────────────
systemctl daemon-reload
systemctl enable beszel-agent
systemctl restart beszel-agent

# ─── Verify ──────────────────────────────────────────────────
sleep 2
if systemctl is-active --quiet beszel-agent; then
    log "beszel-agent is running — node '$NODE_NAME' connected to $HUB_URL"
    log "Check logs with: journalctl -u beszel-agent -f"
else
    die "beszel-agent failed to start — check: journalctl -u beszel-agent -n 50"
fi
